spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/clients/**
            - Path=/clients/swagger-ui.html
            - Path=/clients/v3/api-docs

        - id: comment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/comments/**
            - Path=/comments/swagger-ui.html
            - Path=/comments/v3/api-docs

        - id: contract-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/contracts/**
            - Path=/contracts/swagger-ui.html
            - Path=/contracts/v3/api-docs

        - id: driver-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/drivers/**
            - Path=/drivers/swagger-ui.html
            - Path=/drivers/v3/api-docs

        - id: experience-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/experiences/**
            - Path=/experiences/swagger-ui.html
            - Path=/experiences/v3/api-docs

        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/notifications/**
            - Path=/notifications/swagger-ui.html
            - Path=/notifications/v3/api-docs

        - id: payment-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/cards/**
            - Path=/payments/swagger-ui.html
            - Path=/payments/v3/api-docs

        - id: vehicle-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/vehicles/**
            - Path=/vehicles/swagger-ui.html
            - Path=/vehicles/v3/api-docs

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true